# Generated by Django 4.2 on 2023-04-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('admission_mode', models.CharField(choices=[('R', 'Regular'), ('E', 'External')], default='R', max_length=1)),
                ('joining_batch', models.IntegerField()),
                ('phd_status', models.CharField(choices=[('A', 'Admitted'), ('C', 'Coursework Completed'), ('P', 'Proposal Submitted'), ('T', 'Thesis Submitted'), ('D', 'Degree Awarded'), ('W', 'Withdrawn')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(choices=[('GE', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='GE', max_length=3)),
                ('pwd_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('state', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='students.student')),
            ],
        ),
    ]
