# Generated by Django 4.2 on 2023-04-22 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='joining_batch',
        ),
        migrations.RemoveField(
            model_name='studentpersonaldetails',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(default='cs21resch11001', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='joining_batch',
            field=models.CharField(default='2023_Jan', max_length=10),
            preserve_default=False,
        ),
    ]
