# Generated by Django 4.2 on 2023-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_joining_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='is_pmrf',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='kompalli', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phd_status',
            field=models.CharField(choices=[('A', 'Admitted'), ('B', 'Coursework Completed'), ('C', 'CE Completed'), ('D', 'Proposal Submitted'), ('E', 'JRF-SRF'), ('F', 'OC Completed'), ('G', 'VivaVoce Completed'), ('H', 'Degree Awarded'), ('W', 'Withdrawn')], default='A', max_length=1),
        ),
    ]
