# Generated by Django 4.2 on 2023-04-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_name_student_first_name_student_is_pmrf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpersonaldetails',
            name='personal_email',
        ),
    ]
