# Generated by Django 4.2 on 2023-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentpersonaldetails_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
