# Generated by Django 4.2 on 2023-05-05 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentpersonaldetails_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='joining_batch',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
