# Generated by Django 4.2 on 2023-04-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_remove_student_joining_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgress',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('CE', models.DateField(blank=True, null=True)),
                ('RPS', models.DateField(blank=True, null=True)),
                ('JRF_SRF_CONVERSION', models.DateField(blank=True, null=True)),
                ('OC', models.DateField(blank=True, null=True)),
                ('thesis_submission_date', models.DateField(blank=True, null=True)),
                ('viva_date', models.DateField(blank=True, null=True)),
                ('dc_meet1', models.DateField(blank=True, null=True)),
                ('dc_meet2', models.DateField(blank=True, null=True)),
                ('dc_meet3', models.DateField(blank=True, null=True)),
                ('dc_meet4', models.DateField(blank=True, null=True)),
                ('dc_meet5', models.DateField(blank=True, null=True)),
                ('dc_meet6', models.DateField(blank=True, null=True)),
                ('dc_meet7', models.DateField(blank=True, null=True)),
                ('withdraw_date', models.DateField(blank=True, null=True)),
                ('withdraw_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_awarded', models.CharField(max_length=255)),
                ('convocation_batch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
