# Generated by Django 4.2 on 2023-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_remove_academicprogress_is_ce_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogress',
            name='degree_awarded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
