# Generated by Django 4.2 on 2023-04-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctoralCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_guide', to='professors.professor')),
                ('dc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc1', to='professors.professor')),
                ('dc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc2', to='professors.professor')),
                ('dc3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc3', to='professors.professor')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='professors.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
