# Generated by Django 4.2 on 2023-04-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_joining_batch_and_more'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoralcommittee',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctoralcommittee',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student'),
        ),
    ]
