# Generated by Django 4.2 on 2023-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_remove_doctoralcommittee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
