# Generated by Django 4.2 on 2023-04-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_rename_name_professor_first_name_professor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoralcommittee',
            old_name='co_guide',
            new_name='coguide',
        ),
    ]
